[package]
name = "bevy_vox"
version = "0.3.0"
authors = ["erasin <erasinoo@gmail.com>"]
edition = "2021"
description = "Load MagicaVoxel Vox file for bevy engine "
license = "MIT"
repository = "https://github.com/erasin/bevy_vox"
documentation = "https://docs.rs/bevy_vox"
readme = "README.md"
keywords = ['voxel', 'MagicaVoxel', 'game', 'bevy']
exclude = ["assets", "examples"]

[dependencies]
bevy_ecs = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_app = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_asset = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_render = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_utils = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_pbr = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_scene = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_transform = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_math = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy", rev = "8b27124a801d83a1e92f1136ebd2bc9752c3e9d7" }
anyhow = "1.0.58"
thiserror = "1.0.31"
dot_vox = {version = "4.1.0", git = "https://github.com/ostwilkens/dot_vox.git", branch = "serde"}

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "8f721d8d0ac2e14a46051175f6d3394ed87c7214" }
